require(rCharts)
shinyUI(pageWithSidebar(
  headerPanel("Energy efficiency prediction"),
  sidebarPanel(
    sliderInput(inputId="X1",
                label="Relative Compactness",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X2",
                label="Surface Area ",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X3",
                label="Wall Area ",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X4",
                label=" Roof Area",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X5",
                label="Overall Height",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X6",
                label="Orientation",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X7",
                label="Glazing Area",
                min=0,
                max=500,
                step=.5,
                value=0),
    sliderInput(inputId="X8",
                label="Glazing Area Distribution ",
                min=0,
                max=500,
                step=.5,
                value=0),
    actionButton("plotButton", "PLOT")
  ),
  mainPanel(
    tabsetPanel(
      tabPanel("Predicted values & plot", verbatimTextOutput("Y1"),verbatimTextOutput("Y2"),
               showOutput("pmyChart","nvd3")), 
      tabPanel("Summary",verbatimTextOutput("summa"),verbatimTextOutput("summa2")),
      tabPanel("Training data",dataTableOutput("data")),
      tabPanel("Data source",verbatimTextOutput("data_description"))
    )
  )
))